Update smart source
GeneralMills/gmi_common_dbt_utils pull request #11
Opened 2023-08-25 11:38 UTC by pinakidas

Update the smart_source to consider both `DBT_RUN_ENV` and `DBT_USE_ZDEV_DATASET` while populating the tables during dbt runs

2023-08-25 14:01 UTC, drnielsen requested changes
We must keep backwards compatibility with the current behavior as default.

I think if you set a default on the env var call, it won't error out if it doesn't exist.

Otherwise, we need to change the macro signature to add a new param that defaults to the current behavior.

2023-08-25 14:05 UTC, pinakidas commented
> We must keep backwards compatibility with the current behavior as default.
> 
> I think if you set a default on the env var call, it won't error out if it doesn't exist.
> 
> Otherwise, we need to change the macro signature to add a new param that defaults to the current behavior.

Let me try checking that

2023-08-25 14:42 UTC, pinakidas commented
@drnielsen - updated the code changes

2023-08-28 14:23 UTC, drnielsen commented on README.md
> +> **_NOTE:_**  With gmi_common_dbt_utils >= 0.6.0 to populate the tables in the development environment in standard datasets
I think this would be >=0.7.0.

0.6.0 already exists. Other than that, it all looks good.

2023-08-28 14:28 UTC, pinakidas commented on README.md
> +> **_NOTE:_**  With gmi_common_dbt_utils >= 0.6.0 to populate the tables in the development environment in standard datasets
updated

2023-08-28 14:30 UTC, drnielsen approved these changes
Looks good.

2023-08-28 14:30 UTC, merged